name: Unit Test
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited

env:
  NODE_VERSION: 18

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: npm
      - name: Install depedencies
        run: npm ci
      - name: Run tests
        run: npm run test
  run-build:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: npm
      - name: Install depedencies
        run: npm ci
      - name: Run Build
        run: npm run build
